# NOTE: Generated By HttpRunner v3.1.4
# FROM: har/mubu.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseMubu(HttpRunner):

    config = (
        Config("testcase description")
        .verify(False)
        .variables(**{
            "data_unique_id": "01302980-5f42-4477-adee-578a099263d9",
            "csrf_token": "d44043c4-e8e0-4425-893b-2e1465072455",
        })
    )

    teststeps = [
        Step(
            RunRequest("/")
            .get("https://mubu.com/")
            .with_headers(
                **{
                    "upgrade-insecure-requests": "1",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "none",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "$data_unique_id",
                    "csrf_token": "$csrf_token",
                    "language": "en-US",
                    "country": "US",
                    "data-unique-id": "ab79efe0-3d08-11eb-8cea-196b8f1199e7",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1607839301",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2F",
                    "_ga": "GA1.2.517603191.1607839302",
                    "_gid": "GA1.2.1969523483.1607839302",
                    "reg_prepareId": "1765ab60f7d-1765ab60e81-4572-b27a-d4ea0c1a5b9f",
                    "reg_focusId": "59e3df3d-7d53-4572-b27a-1765ab6148f",
                    "use-redesign": "1",
                    "_gat_UA-77727571-3": "1",
                    "SESSION": "2689b880-46b2-40b9-b63b-89332adfa410",
                    "SLARDAR_WEB_ID": "5ab10989-9335-420f-932d-2255be13c9fd",
                    "_gat": "1",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1607839822",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/login")
            .get("https://mubu.com/login")
            .with_headers(
                **{
                    "upgrade-insecure-requests": "1",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "$data_unique_id",
                    "csrf_token": "$csrf_token",
                    "language": "en-US",
                    "country": "US",
                    "data-unique-id": "ab79efe0-3d08-11eb-8cea-196b8f1199e7",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1607839301",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2F",
                    "_ga": "GA1.2.517603191.1607839302",
                    "_gid": "GA1.2.1969523483.1607839302",
                    "reg_prepareId": "1765ab60f7d-1765ab60e81-4572-b27a-d4ea0c1a5b9f",
                    "reg_focusId": "59e3df3d-7d53-4572-b27a-1765ab6148f",
                    "use-redesign": "1",
                    "_gat_UA-77727571-3": "1",
                    "SESSION": "2689b880-46b2-40b9-b63b-89332adfa410",
                    "_gat": "1",
                    "SLARDAR_WEB_ID": "e0508847-05a7-4bbe-ae74-de0e6e6ad076",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1607839835",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/login/password")
            .get("https://mubu.com/login/password")
            .with_headers(
                **{
                    "upgrade-insecure-requests": "1",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "referer": "https://mubu.com/login",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "$data_unique_id",
                    "csrf_token": "$csrf_token",
                    "language": "en-US",
                    "country": "US",
                    "data-unique-id": "ab79efe0-3d08-11eb-8cea-196b8f1199e7",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1607839301",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2F",
                    "_ga": "GA1.2.517603191.1607839302",
                    "_gid": "GA1.2.1969523483.1607839302",
                    "use-redesign": "1",
                    "SESSION": "2689b880-46b2-40b9-b63b-89332adfa410",
                    "_gat": "1",
                    "SLARDAR_WEB_ID": "b1b8dea7-a136-4040-8ea1-54c846faf78c",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1607839842",
                    "reg_prepareId": "1765ab8fe62-1765ab8fd1c-477f-be8e-389fe75827db",
                    "reg_focusId": "9ca61e84-c521-477f-be8e-1765ab90208",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/api/login/submit")
            .post("https://mubu.com/api/login/submit")
            .with_headers(
                **{
                    "content-length": "65",
                    "accept": "application/json, text/javascript, */*; q=0.01",
                    "x-requested-with": "XMLHttpRequest",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/login/password",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "$data_unique_id",
                    "csrf_token": "$csrf_token",
                    "language": "en-US",
                    "country": "US",
                    "data-unique-id": "ab79efe0-3d08-11eb-8cea-196b8f1199e7",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1607839301",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2F",
                    "_ga": "GA1.2.517603191.1607839302",
                    "_gid": "GA1.2.1969523483.1607839302",
                    "use-redesign": "1",
                    "SESSION": "2689b880-46b2-40b9-b63b-89332adfa410",
                    "_gat": "1",
                    "reg_prepareId": "1765ab8fe62-1765ab8fd1c-477f-be8e-389fe75827db",
                    "reg_focusId": "9ca61e84-c521-477f-be8e-1765ab90208",
                    "SLARDAR_WEB_ID": "2b7089bd-3888-4058-8f2e-26be835123ac",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1607839844",
                }
            )
            .with_data(
                {
                    "phone": "18613143458",
                    "password": "mtFrwy$!kt3RTRq@QpqW",
                    "remember": "true",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
        ),
        Step(
            RunRequest("/app")
            .get("https://mubu.com/app")
            .with_headers(
                **{
                    "upgrade-insecure-requests": "1",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "referer": "https://mubu.com/login/password",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "$data_unique_id",
                    "csrf_token": "$csrf_token",
                    "language": "en-US",
                    "country": "US",
                    "data-unique-id": "ab79efe0-3d08-11eb-8cea-196b8f1199e7",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1607839301",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2F",
                    "_ga": "GA1.2.517603191.1607839302",
                    "_gid": "GA1.2.1969523483.1607839302",
                    "use-redesign": "1",
                    "SESSION": "2689b880-46b2-40b9-b63b-89332adfa410",
                    "_gat": "1",
                    "reg_prepareId": "1765ab8fe62-1765ab8fd1c-477f-be8e-389fe75827db",
                    "reg_focusId": "9ca61e84-c521-477f-be8e-1765ab90208",
                    "SLARDAR_WEB_ID": "2b7089bd-3888-4058-8f2e-26be835123ac",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1607839844",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTQ0OTE2NCIsImV4cCI6MTYxMDQzMTg0NiwiaWF0IjoxNjA3ODM5ODQ2fQ.Wj8zWxDskNCkl5U0YVEcku00glmEukoaIiJFvgXikhq5vltViRv39Rp4Z2A9eiAS-UENG-ENKtmWfhwRr6j47w",
                    "user_persistence": "98f3e157-7fcc-42b4-b303-eed91ae5fac7",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/")
            .get("https://api2.mubu.com/v3/")
            .with_headers(
                **{
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "accept": "image/avif,image/webp,image/apng,image/*,*/*;q=0.8",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "no-cors",
                    "sec-fetch-dest": "image",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1607839301",
                    "_ga": "GA1.2.517603191.1607839302",
                    "_gid": "GA1.2.1969523483.1607839302",
                    "use-redesign": "1",
                    "_gat": "1",
                    "SLARDAR_WEB_ID": "2b7089bd-3888-4058-8f2e-26be835123ac",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1607839844",
                    "_gat_UA-77727571-3": "1",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 17)
            .assert_equal("body.msg", "illegal request")
        ),
        Step(
            RunRequest("/v3/api/message/get_message_unread")
            .post("https://api2.mubu.com/v3/api/message/get_message_unread")
            .with_headers(
                **{
                    "content-length": "10",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTQ0OTE2NCIsImV4cCI6MTYxMDQzMTg0NiwiaWF0IjoxNjA3ODM5ODQ2fQ.Wj8zWxDskNCkl5U0YVEcku00glmEukoaIiJFvgXikhq5vltViRv39Rp4Z2A9eiAS-UENG-ENKtmWfhwRr6j47w",
                    "content-type": "application/json;charset=UTF-8",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "data-unique-id": "ab79efe0-3d08-11eb-8cea-196b8f1199e7",
                    "x-request-id": "1fbb1ccd-23ba-4836-ad14-141a2c99cc21",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
            .with_json({"page": 1})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/user/profile")
            .post("https://api2.mubu.com/v3/api/user/profile")
            .with_headers(
                **{
                    "content-length": "0",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTQ0OTE2NCIsImV4cCI6MTYxMDQzMTg0NiwiaWF0IjoxNjA3ODM5ODQ2fQ.Wj8zWxDskNCkl5U0YVEcku00glmEukoaIiJFvgXikhq5vltViRv39Rp4Z2A9eiAS-UENG-ENKtmWfhwRr6j47w",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "data-unique-id": "ab79efe0-3d08-11eb-8cea-196b8f1199e7",
                    "x-request-id": "01ec77e4-3ad0-4967-af31-a6d319f186de",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/get_all_documents_page")
            .post("https://api2.mubu.com/v3/api/list/get_all_documents_page")
            .with_headers(
                **{
                    "content-length": "12",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTQ0OTE2NCIsImV4cCI6MTYxMDQzMTg0NiwiaWF0IjoxNjA3ODM5ODQ2fQ.Wj8zWxDskNCkl5U0YVEcku00glmEukoaIiJFvgXikhq5vltViRv39Rp4Z2A9eiAS-UENG-ENKtmWfhwRr6j47w",
                    "content-type": "application/json;charset=UTF-8",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "data-unique-id": "ab79efe0-3d08-11eb-8cea-196b8f1199e7",
                    "x-request-id": "c110bae5-09c6-4671-b969-986bba36dc09",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
            .with_json({"start": ""})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/user/get_user_params")
            .post("https://api2.mubu.com/v3/api/user/get_user_params")
            .with_headers(
                **{
                    "content-length": "0",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTQ0OTE2NCIsImV4cCI6MTYxMDQzMTg0NiwiaWF0IjoxNjA3ODM5ODQ2fQ.Wj8zWxDskNCkl5U0YVEcku00glmEukoaIiJFvgXikhq5vltViRv39Rp4Z2A9eiAS-UENG-ENKtmWfhwRr6j47w",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "data-unique-id": "ab79efe0-3d08-11eb-8cea-196b8f1199e7",
                    "x-request-id": "ba0cc12a-8b1f-4d2a-be61-5195664f30ae",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/star_relation/get")
            .get("https://api2.mubu.com/v3/api/list/star_relation/get")
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTQ0OTE2NCIsImV4cCI6MTYxMDQzMTg0NiwiaWF0IjoxNjA3ODM5ODQ2fQ.Wj8zWxDskNCkl5U0YVEcku00glmEukoaIiJFvgXikhq5vltViRv39Rp4Z2A9eiAS-UENG-ENKtmWfhwRr6j47w",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "data-unique-id": "ab79efe0-3d08-11eb-8cea-196b8f1199e7",
                    "x-request-id": "d31be92c-f40d-4a32-b6c6-07654b248b1a",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/item_count")
            .post("https://api2.mubu.com/v3/api/list/item_count")
            .with_headers(
                **{
                    "content-length": "30",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTQ0OTE2NCIsImV4cCI6MTYxMDQzMTg0NiwiaWF0IjoxNjA3ODM5ODQ2fQ.Wj8zWxDskNCkl5U0YVEcku00glmEukoaIiJFvgXikhq5vltViRv39Rp4Z2A9eiAS-UENG-ENKtmWfhwRr6j47w",
                    "content-type": "application/json;charset=UTF-8",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "data-unique-id": "ab79efe0-3d08-11eb-8cea-196b8f1199e7",
                    "x-request-id": "7545ec39-3de0-44db-aa7c-355988056438",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
            .with_json({"folderId": 0, "source": "home"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/advertisement/get")
            .post("https://api2.mubu.com/v3/api/advertisement/get")
            .with_headers(
                **{
                    "content-length": "10",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTQ0OTE2NCIsImV4cCI6MTYxMDQzMTg0NiwiaWF0IjoxNjA3ODM5ODQ2fQ.Wj8zWxDskNCkl5U0YVEcku00glmEukoaIiJFvgXikhq5vltViRv39Rp4Z2A9eiAS-UENG-ENKtmWfhwRr6j47w",
                    "content-type": "application/json;charset=UTF-8",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "data-unique-id": "ab79efe0-3d08-11eb-8cea-196b8f1199e7",
                    "x-request-id": "9df88dd4-2e3f-48f7-adfe-f9c27880be63",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
            .with_json({"type": 1})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/item_count")
            .post("https://api2.mubu.com/v3/api/list/item_count")
            .with_headers(
                **{
                    "content-length": "30",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTQ0OTE2NCIsImV4cCI6MTYxMDQzMTg0NiwiaWF0IjoxNjA3ODM5ODQ2fQ.Wj8zWxDskNCkl5U0YVEcku00glmEukoaIiJFvgXikhq5vltViRv39Rp4Z2A9eiAS-UENG-ENKtmWfhwRr6j47w",
                    "content-type": "application/json;charset=UTF-8",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "data-unique-id": "ab79efe0-3d08-11eb-8cea-196b8f1199e7",
                    "x-request-id": "7545ec39-3de0-44db-aa7c-355988056438",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
            .with_json({"folderId": 0, "source": "home"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/create_folder")
            .post("https://api2.mubu.com/v3/api/list/create_folder")
            .with_headers(
                **{
                    "content-length": "39",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTQ0OTE2NCIsImV4cCI6MTYxMDQzMTg0NiwiaWF0IjoxNjA3ODM5ODQ2fQ.Wj8zWxDskNCkl5U0YVEcku00glmEukoaIiJFvgXikhq5vltViRv39Rp4Z2A9eiAS-UENG-ENKtmWfhwRr6j47w",
                    "content-type": "application/json;charset=UTF-8",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "data-unique-id": "ab79efe0-3d08-11eb-8cea-196b8f1199e7",
                    "x-request-id": "232a4cbc-ded7-4d84-80b7-961234923811",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
            .with_json({"name": "hogwarts-demo", "folderId": "0"})
            .extract()
            .with_jmespath("headers.server", "server")
            .with_jmespath("body.data.folder.id", "folderId")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/item_count")
            .post("https://api2.mubu.com/v3/api/list/item_count")
            .with_headers(
                **{
                    "content-length": "42",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTQ0OTE2NCIsImV4cCI6MTYxMDQzMTg0NiwiaWF0IjoxNjA3ODM5ODQ2fQ.Wj8zWxDskNCkl5U0YVEcku00glmEukoaIiJFvgXikhq5vltViRv39Rp4Z2A9eiAS-UENG-ENKtmWfhwRr6j47w",
                    "content-type": "application/json;charset=UTF-8",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "data-unique-id": "ab79efe0-3d08-11eb-8cea-196b8f1199e7",
                    "x-request-id": "99a27a85-0bdd-49e4-af6d-1737c562b789",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
            .with_json({"folderId": "$folderId", "source": "home"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/create_doc")
            .post("https://api2.mubu.com/v3/api/list/create_doc")
            .with_headers(
                **{
                    "content-length": "35",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTQ0OTE2NCIsImV4cCI6MTYxMDQzMTg0NiwiaWF0IjoxNjA3ODM5ODQ2fQ.Wj8zWxDskNCkl5U0YVEcku00glmEukoaIiJFvgXikhq5vltViRv39Rp4Z2A9eiAS-UENG-ENKtmWfhwRr6j47w",
                    "content-type": "application/json;charset=UTF-8",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "data-unique-id": "ab79efe0-3d08-11eb-8cea-196b8f1199e7",
                    "x-request-id": "a77965bb-9ef3-4f98-a1e2-c73769a29d9d",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
            .with_json({"folderId": "$folderId", "type": 0})
            .extract()
            .with_jmespath("body.data.id", "docId")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/item_count")
            .post("https://api2.mubu.com/v3/api/list/item_count")
            .with_headers(
                **{
                    "content-length": "30",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTQ0OTE2NCIsImV4cCI6MTYxMDQzMTg0NiwiaWF0IjoxNjA3ODM5ODQ2fQ.Wj8zWxDskNCkl5U0YVEcku00glmEukoaIiJFvgXikhq5vltViRv39Rp4Z2A9eiAS-UENG-ENKtmWfhwRr6j47w",
                    "content-type": "application/json;charset=UTF-8",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "data-unique-id": "ab79efe0-3d08-11eb-8cea-196b8f1199e7",
                    "x-request-id": "922db773-309a-4caf-8c3d-56c8f6628b32",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
            .with_json({"folderId": 0, "source": "home"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/user/current_level")
            .post("https://api2.mubu.com/v3/api/user/current_level")
            .with_headers(
                **{
                    "content-length": "29",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTQ0OTE2NCIsImV4cCI6MTYxMDQzMTg0NiwiaWF0IjoxNjA3ODM5ODQ2fQ.Wj8zWxDskNCkl5U0YVEcku00glmEukoaIiJFvgXikhq5vltViRv39Rp4Z2A9eiAS-UENG-ENKtmWfhwRr6j47w",
                    "content-type": "application/json;charset=UTF-8",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "data-unique-id": "ab79efe0-3d08-11eb-8cea-196b8f1199e7",
                    "x-request-id": "1b63b430-df71-4068-9cf5-bce9a0a09e70",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
            .with_json({"document_id": "$docId"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/document/edit/get")
            .post("https://api2.mubu.com/v3/api/document/edit/get")
            .with_headers(
                **{
                    "content-length": "37",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTQ0OTE2NCIsImV4cCI6MTYxMDQzMTg0NiwiaWF0IjoxNjA3ODM5ODQ2fQ.Wj8zWxDskNCkl5U0YVEcku00glmEukoaIiJFvgXikhq5vltViRv39Rp4Z2A9eiAS-UENG-ENKtmWfhwRr6j47w",
                    "content-type": "application/json;charset=UTF-8",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "data-unique-id": "ab79efe0-3d08-11eb-8cea-196b8f1199e7",
                    "x-request-id": "bd9ea5f3-4526-4c52-8bc3-5c7175c79755",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
            .with_json({"docId": "$docId", "password": ""})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/user/get_invite_count")
            .get("https://api2.mubu.com/v3/api/user/get_invite_count")
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTQ0OTE2NCIsImV4cCI6MTYxMDQzMTg0NiwiaWF0IjoxNjA3ODM5ODQ2fQ.Wj8zWxDskNCkl5U0YVEcku00glmEukoaIiJFvgXikhq5vltViRv39Rp4Z2A9eiAS-UENG-ENKtmWfhwRr6j47w",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "data-unique-id": "ab79efe0-3d08-11eb-8cea-196b8f1199e7",
                    "x-request-id": "95565b91-5ed9-41f1-9399-ea60159586fc",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/register")
            .get("https://api2.mubu.com/v3/api/colla/register")
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTQ0OTE2NCIsImV4cCI6MTYxMDQzMTg0NiwiaWF0IjoxNjA3ODM5ODQ2fQ.Wj8zWxDskNCkl5U0YVEcku00glmEukoaIiJFvgXikhq5vltViRv39Rp4Z2A9eiAS-UENG-ENKtmWfhwRr6j47w",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "data-unique-id": "ab79efe0-3d08-11eb-8cea-196b8f1199e7",
                    "x-request-id": "912fd950-e33b-4567-af08-105d5de5035e",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/members")
            .options("https://api2.mubu.com/v3/api/colla/members")
            .with_params(**{"memberId": "1715103091276471", "documentId": "$docId"})
            .with_headers(
                **{
                    "accept": "*/*",
                    "access-control-request-method": "GET",
                    "access-control-request-headers": "data-unique-id,jwt-token,request-id,x-request-id",
                    "origin": "https://mubu.com",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/colla/members")
            .get("https://api2.mubu.com/v3/api/colla/members")
            .with_params(**{"memberId": "1715103091276471", "documentId": "$docId"})
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTQ0OTE2NCIsImV4cCI6MTYxMDQzMTg0NiwiaWF0IjoxNjA3ODM5ODQ2fQ.Wj8zWxDskNCkl5U0YVEcku00glmEukoaIiJFvgXikhq5vltViRv39Rp4Z2A9eiAS-UENG-ENKtmWfhwRr6j47w",
                    "request-id": "members:1715103091276471:1607839891209",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "data-unique-id": "ab79efe0-3d08-11eb-8cea-196b8f1199e7",
                    "x-request-id": "e46a2eab-733e-4313-91fc-69334f01a4a0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "404",
                    "member-id": "1715103091276471",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "data-unique-id": "ab79efe0-3d08-11eb-8cea-196b8f1199e7",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTQ0OTE2NCIsImV4cCI6MTYxMDQzMTg0NiwiaWF0IjoxNjA3ODM5ODQ2fQ.Wj8zWxDskNCkl5U0YVEcku00glmEukoaIiJFvgXikhq5vltViRv39Rp4Z2A9eiAS-UENG-ENKtmWfhwRr6j47w",
                    "request-id": "MESSAGE:1449164:1715103091276471:3",
                    "x-request-id": "27d542c9-0264-4ffd-924f-e7179a88eea3",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 3,
                    "requestId": "MESSAGE:1449164:1715103091276471:3",
                    "token": "$docId",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "$docId",
                            "version": 0,
                            "content": [
                                {"name": "nameChanged", "title": "d", "original": ""},
                                {"name": "nameChanged", "title": "de", "original": "d"},
                            ],
                        }
                    },
                    "context": {
                        "os": "macOS",
                        "osVersion": "11.0.1",
                        "appVersion": "2.0.0.373",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "412",
                    "member-id": "1715103091276471",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "data-unique-id": "ab79efe0-3d08-11eb-8cea-196b8f1199e7",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTQ0OTE2NCIsImV4cCI6MTYxMDQzMTg0NiwiaWF0IjoxNjA3ODM5ODQ2fQ.Wj8zWxDskNCkl5U0YVEcku00glmEukoaIiJFvgXikhq5vltViRv39Rp4Z2A9eiAS-UENG-ENKtmWfhwRr6j47w",
                    "request-id": "MESSAGE:1449164:1715103091276471:6",
                    "x-request-id": "9c9ef198-b7ff-4135-b00b-7353b7efecf2",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 6,
                    "requestId": "MESSAGE:1449164:1715103091276471:6",
                    "token": "$docId",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "$docId",
                            "version": 1,
                            "content": [
                                {
                                    "name": "nameChanged",
                                    "title": "dem",
                                    "original": "de",
                                },
                                {
                                    "name": "nameChanged",
                                    "title": "demo",
                                    "original": "dem",
                                },
                            ],
                        }
                    },
                    "context": {
                        "os": "macOS",
                        "osVersion": "11.0.1",
                        "appVersion": "2.0.0.373",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "653",
                    "member-id": "1715103091276471",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "data-unique-id": "ab79efe0-3d08-11eb-8cea-196b8f1199e7",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTQ0OTE2NCIsImV4cCI6MTYxMDQzMTg0NiwiaWF0IjoxNjA3ODM5ODQ2fQ.Wj8zWxDskNCkl5U0YVEcku00glmEukoaIiJFvgXikhq5vltViRv39Rp4Z2A9eiAS-UENG-ENKtmWfhwRr6j47w",
                    "request-id": "MESSAGE:1449164:1715103091276471:7",
                    "x-request-id": "63825f48-7d42-4916-9360-53e4fac21c00",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 7,
                    "requestId": "MESSAGE:1449164:1715103091276471:7",
                    "token": "$docId",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "$docId",
                            "version": 2,
                            "content": [
                                {
                                    "name": "create",
                                    "created": [
                                        {
                                            "index": 0,
                                            "parentId": None,
                                            "node": {
                                                "id": "mJNWbfiORR",
                                                "text": "",
                                                "modified": 1607839895792,
                                                "children": [],
                                            },
                                            "path": ["nodes", 0],
                                        }
                                    ],
                                },
                                {
                                    "name": "update",
                                    "updated": [
                                        {
                                            "updated": {
                                                "id": "mJNWbfiORR",
                                                "text": "<span>1</span>",
                                                "modified": 1607839896235,
                                            },
                                            "original": {
                                                "id": "mJNWbfiORR",
                                                "text": "",
                                                "modified": 1607839895792,
                                            },
                                            "path": ["nodes", 0],
                                        }
                                    ],
                                },
                            ],
                        }
                    },
                    "context": {
                        "os": "macOS",
                        "osVersion": "11.0.1",
                        "appVersion": "2.0.0.373",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "516",
                    "member-id": "1715103091276471",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "data-unique-id": "ab79efe0-3d08-11eb-8cea-196b8f1199e7",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTQ0OTE2NCIsImV4cCI6MTYxMDQzMTg0NiwiaWF0IjoxNjA3ODM5ODQ2fQ.Wj8zWxDskNCkl5U0YVEcku00glmEukoaIiJFvgXikhq5vltViRv39Rp4Z2A9eiAS-UENG-ENKtmWfhwRr6j47w",
                    "request-id": "MESSAGE:1449164:1715103091276471:9",
                    "x-request-id": "9edcff79-d4bb-4074-bc0b-238690eab72d",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 9,
                    "requestId": "MESSAGE:1449164:1715103091276471:9",
                    "token": "$docId",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "$docId",
                            "version": 3,
                            "content": [
                                {
                                    "name": "update",
                                    "updated": [
                                        {
                                            "updated": {
                                                "id": "mJNWbfiORR",
                                                "text": "<span>111</span>",
                                                "modified": 1607839896727,
                                            },
                                            "original": {
                                                "id": "mJNWbfiORR",
                                                "text": "<span>1</span>",
                                                "modified": 1607839896235,
                                            },
                                            "path": ["nodes", 0],
                                        }
                                    ],
                                }
                            ],
                        }
                    },
                    "context": {
                        "os": "macOS",
                        "osVersion": "11.0.1",
                        "appVersion": "2.0.0.373",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "459",
                    "member-id": "1715103091276471",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "data-unique-id": "ab79efe0-3d08-11eb-8cea-196b8f1199e7",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTQ0OTE2NCIsImV4cCI6MTYxMDQzMTg0NiwiaWF0IjoxNjA3ODM5ODQ2fQ.Wj8zWxDskNCkl5U0YVEcku00glmEukoaIiJFvgXikhq5vltViRv39Rp4Z2A9eiAS-UENG-ENKtmWfhwRr6j47w",
                    "request-id": "MESSAGE:1449164:1715103091276471:11",
                    "x-request-id": "bc590d98-a457-48d1-9308-0edc82def20d",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 11,
                    "requestId": "MESSAGE:1449164:1715103091276471:11",
                    "token": "$docId",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "$docId",
                            "version": 4,
                            "content": [
                                {
                                    "name": "create",
                                    "created": [
                                        {
                                            "index": 1,
                                            "parentId": None,
                                            "node": {
                                                "id": "wREJaChMWv",
                                                "text": "",
                                                "modified": 1607839897216,
                                                "children": [],
                                            },
                                            "path": ["nodes", 1],
                                        }
                                    ],
                                }
                            ],
                        }
                    },
                    "context": {
                        "os": "macOS",
                        "osVersion": "11.0.1",
                        "appVersion": "2.0.0.373",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "502",
                    "member-id": "1715103091276471",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "data-unique-id": "ab79efe0-3d08-11eb-8cea-196b8f1199e7",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTQ0OTE2NCIsImV4cCI6MTYxMDQzMTg0NiwiaWF0IjoxNjA3ODM5ODQ2fQ.Wj8zWxDskNCkl5U0YVEcku00glmEukoaIiJFvgXikhq5vltViRv39Rp4Z2A9eiAS-UENG-ENKtmWfhwRr6j47w",
                    "request-id": "MESSAGE:1449164:1715103091276471:13",
                    "x-request-id": "595ecc48-b6e0-4da2-8d70-ae0e87888833",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 13,
                    "requestId": "MESSAGE:1449164:1715103091276471:13",
                    "token": "$docId",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "$docId",
                            "version": 5,
                            "content": [
                                {
                                    "name": "update",
                                    "updated": [
                                        {
                                            "updated": {
                                                "id": "wREJaChMWv",
                                                "text": "<span>2</span>",
                                                "modified": 1607839897641,
                                            },
                                            "original": {
                                                "id": "wREJaChMWv",
                                                "text": "",
                                                "modified": 1607839897216,
                                            },
                                            "path": ["nodes", 1],
                                        }
                                    ],
                                }
                            ],
                        }
                    },
                    "context": {
                        "os": "macOS",
                        "osVersion": "11.0.1",
                        "appVersion": "2.0.0.373",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "518",
                    "member-id": "1715103091276471",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "data-unique-id": "ab79efe0-3d08-11eb-8cea-196b8f1199e7",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTQ0OTE2NCIsImV4cCI6MTYxMDQzMTg0NiwiaWF0IjoxNjA3ODM5ODQ2fQ.Wj8zWxDskNCkl5U0YVEcku00glmEukoaIiJFvgXikhq5vltViRv39Rp4Z2A9eiAS-UENG-ENKtmWfhwRr6j47w",
                    "request-id": "MESSAGE:1449164:1715103091276471:14",
                    "x-request-id": "56f5531a-fb9d-4f3e-8e90-2483aecc0f4f",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 14,
                    "requestId": "MESSAGE:1449164:1715103091276471:14",
                    "token": "$docId",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "$docId",
                            "version": 6,
                            "content": [
                                {
                                    "name": "update",
                                    "updated": [
                                        {
                                            "updated": {
                                                "id": "wREJaChMWv",
                                                "text": "<span>222</span>",
                                                "modified": 1607839898379,
                                            },
                                            "original": {
                                                "id": "wREJaChMWv",
                                                "text": "<span>2</span>",
                                                "modified": 1607839897641,
                                            },
                                            "path": ["nodes", 1],
                                        }
                                    ],
                                }
                            ],
                        }
                    },
                    "context": {
                        "os": "macOS",
                        "osVersion": "11.0.1",
                        "appVersion": "2.0.0.373",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/item_count")
            .post("https://api2.mubu.com/v3/api/list/item_count")
            .with_headers(
                **{
                    "content-length": "42",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTQ0OTE2NCIsImV4cCI6MTYxMDQzMTg0NiwiaWF0IjoxNjA3ODM5ODQ2fQ.Wj8zWxDskNCkl5U0YVEcku00glmEukoaIiJFvgXikhq5vltViRv39Rp4Z2A9eiAS-UENG-ENKtmWfhwRr6j47w",
                    "content-type": "application/json;charset=UTF-8",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "data-unique-id": "ab79efe0-3d08-11eb-8cea-196b8f1199e7",
                    "x-request-id": "00593f19-dee2-447c-96a1-82a53c10b6a0",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
            .with_json({"folderId": "$folderId", "source": "home"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "226",
                    "member-id": "1715103091276471",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "data-unique-id": "ab79efe0-3d08-11eb-8cea-196b8f1199e7",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTQ0OTE2NCIsImV4cCI6MTYxMDQzMTg0NiwiaWF0IjoxNjA3ODM5ODQ2fQ.Wj8zWxDskNCkl5U0YVEcku00glmEukoaIiJFvgXikhq5vltViRv39Rp4Z2A9eiAS-UENG-ENKtmWfhwRr6j47w",
                    "request-id": "MESSAGE:1449164:1715103091276471:17",
                    "x-request-id": "6e0fb314-3179-4320-81c9-b75814402271",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "UNWATCH",
                    "reqId": 17,
                    "requestId": "MESSAGE:1449164:1715103091276471:17",
                    "token": "$docId",
                    "data": {},
                    "context": {
                        "os": "macOS",
                        "osVersion": "11.0.1",
                        "appVersion": "2.0.0.373",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseMubu().test_start()
